name: hosegment
channels:
  - pytorch 
  - conda-forge   
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch==1.12.0
  - cudatoolkit==11.6  
  - torchvision==0.13.0
  - pillow
  - pip:
    - scikit-image
    - imageio-ffmpeg
    - opencv-python
    - streamlit-webrtc
    - timm==0.6.7
    - tqdm
    - matplotlib